export default {
    repositories: {
        terms: {
            noubar: [
                {
                    name: 'noubar',
                    full_name: 'full name',
                    owner: { login: 'noubar', html_url: '/' },
                    html_url: '/',
                    stargazers_count: 10,
                    description: 'awesome repo',
                    email: null,
                    language: 'javascript',
                },
                {
                    name: 'noubar',
                    full_name: 'full name',
                    owner: { login: 'noubar', html_url: '/' },
                    html_url: '/',
                    stargazers_count: 10,
                    description: 'awesome repo',
                    email: null,
                    language: 'javascript',
                },
                {
                    name: 'noubar',
                    full_name: 'full name',
                    owner: { login: 'noubar', html_url: '/' },
                    html_url: '/',
                    stargazers_count: 10,
                    description: 'awesome repo',
                    email: null,
                    language: 'javascript',
                },
            ],
        },
    },
    userData: [
        {
            name: 'noubar',
            full_name: 'full name',
            owner: { login: 'noubar', html_url: '/' },
            html_url: '/',
            stargazers_count: 10,
            description: 'awesome repo',
            email: null,
            language: 'javascript',
        },
        {
            name: 'noubar',
            full_name: 'full name',
            owner: { login: 'noubar', html_url: '/' },
            html_url: '/',
            stargazers_count: 10,
            description: 'awesome repo',
            email: null,
            language: 'javascript',
        },
        {
            name: 'noubar',
            full_name: 'full name',
            owner: { login: 'noubar', html_url: '/' },
            html_url: '/',
            stargazers_count: 10,
            description: 'awesome repo',
            email: null,
            language: '',
        },
    ],
};
